name: proto-gen

on:
  push:
    branches: [ main ]

env:
  KAI_PROTO_PATH: ${{ github.WORKSPACE }}/dreamstaxapis
  KAI_GO_GENPROTO_PATH: ${{ github.WORKSPACE }}/go-genproto
  API_COMMON_PROTO_PATH: ${{ github.WORKSPACE }}/api-common-protos

jobs:
  gen-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dreamstaxapis

      - uses: actions/checkout@v4
        with:
          repository: dreamstax/go-genproto
          path: go-genproto

      - uses: actions/checkout@v4
        with:
          repository: googleapis/api-common-protos
          path: api-common-protos

      - name: setup protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '24.x'

      - name: install build tools
        run: |
          cd dreamstaxapis
          make install
          make gen

